AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 instance with SSM access, Apache installed, and public IP

Parameters:
  ImageId:
    Type: String
    Description: AMI ID for the instance (e.g., ami-0100e595e1cc1ff7f for Amazon Linux 2 in us-east-2)
    Default: ami-0100e595e1cc1ff7f

  VpcId:
    Type: String
    Description: VPC ID where the instance will be launched
    Default: vpc-0a55ce42c45c2c211

  SubnetId:
    Type: String
    Description: Subnet ID where the instance will be launched
    Default: subnet-09c82d8f0c19e14c1

  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro

  KeyName:
    Type: String
    Description: EC2 Key Pair name for SSH access
    Default: testkey

Resources:
  MyInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all traffic from anywhere (insecure - for lab/demo purposes only)
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  MyInstanceIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref MyInstanceIAMRole
      Path: /

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref MyInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          SubnetId: !Ref SubnetId
          DeviceIndex: 0
          GroupSet:
            - !Ref MyInstanceSecurityGroup
      Tags:
        - Key: Name
          Value: MyApacheSSMInstance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl enable httpd
          systemctl start httpd
          echo "<h1>Hello from EC2 with Apache via CloudFormation</h1>" > /var/www/html/index.html
