AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy EC2 instances into subnets across peered VPCs with SSM access and intra-VPC communication

Parameters:
  PeerAVPCSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID in VPC-A (10.0.0.0/16)
  PeerBVPCSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID in VPC-B (11.0.0.0/16)

Resources:
  InstanceIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: /

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceIAMRole
      Path: /

  PeerVPCSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic between peered VPCs only (10.0.0.0/16 <-> 11.0.0.0/16)
      VpcId: vpc-0cdd4fc9f443a7e7f # Replace with Peer-A VPC ID
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 11.0.0.0/16
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  PeerAInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0100e595e1cc1ff7f
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref PeerAVPCSubnetId
          GroupSet:
            - !Ref PeerVPCSecurityGroup
      Tags:
        - Key: Name
          Value: PeerA-SSM-Instance

  PeerBInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0100e595e1cc1ff7f
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref PeerBVPCSubnetId
          GroupSet:
            - !Ref PeerVPCSecurityGroup
      Tags:
        - Key: Name
          Value: PeerB-SSM-Instance
