AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy EC2 instance in VPC-A with SSM access

Parameters:
  PeerAVPCSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID in VPC-A (10.0.0.0/16)

Resources:
  InstanceIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: /

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceIAMRole
      Path: /

  PeerASecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from VPC-B CIDR (11.0.0.0/16)
      VpcId: vpc-0e8c1d640922215c1 # VPC-A
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 11.0.0.0/16
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 10.0.0.0/16
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  PeerAInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0100e595e1cc1ff7f
      KeyName: testkey
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref PeerAVPCSubnetId
          AssociatePublicIpAddress: true
          GroupSet:
            - !Ref PeerASecurityGroup
      Tags:
        - Key: Name
          Value: PeerA-SSM-Instance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl enable httpd
          systemctl start httpd
          echo "<h1>Hello from EC2 with Apache via CloudFormation</h1>" > /var/www/html/index.html
